[{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "2657",
	"severity": 8,
	"message": "JSX expressions must have one parent element.",
	"source": "ts",
	"startLineNumber": 407,
	"startColumn": 9,
	"endLineNumber": 485,
	"endColumn": 20,
	"modelVersionId": 59,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "2322",
	"severity": 8,
	"message": "Type '(e: any) => any' is not assignable to type 'ReactNode'.",
	"source": "ts",
	"startLineNumber": 432,
	"startColumn": 25,
	"endLineNumber": 432,
	"endColumn": 53,
	"modelVersionId": 59,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'e' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 432,
	"startColumn": 27,
	"endLineNumber": 432,
	"endColumn": 28,
	"modelVersionId": 59,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 433,
	"startColumn": 15,
	"endLineNumber": 433,
	"endColumn": 16,
	"modelVersionId": 59,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "17002",
	"severity": 8,
	"message": "Expected corresponding JSX closing tag for 'div'.",
	"source": "ts",
	"startLineNumber": 435,
	"startColumn": 17,
	"endLineNumber": 435,
	"endColumn": 18,
	"modelVersionId": 59,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "')' expected.",
	"source": "ts",
	"startLineNumber": 486,
	"startColumn": 9,
	"endLineNumber": 486,
	"endColumn": 11,
	"modelVersionId": 59,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "17002",
	"severity": 8,
	"message": "Expected corresponding JSX closing tag for 'main'.",
	"source": "ts",
	"startLineNumber": 486,
	"startColumn": 11,
	"endLineNumber": 486,
	"endColumn": 14,
	"modelVersionId": 59,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'showDeleteAlbum'.",
	"source": "ts",
	"startLineNumber": 489,
	"startColumn": 8,
	"endLineNumber": 489,
	"endColumn": 23,
	"modelVersionId": 59,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'setShowDeleteAlbum'.",
	"source": "ts",
	"startLineNumber": 490,
	"startColumn": 61,
	"endLineNumber": 490,
	"endColumn": 79,
	"modelVersionId": 59,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'album'.",
	"source": "ts",
	"startLineNumber": 495,
	"startColumn": 53,
	"endLineNumber": 495,
	"endColumn": 58,
	"modelVersionId": 59,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'photos'.",
	"source": "ts",
	"startLineNumber": 495,
	"startColumn": 84,
	"endLineNumber": 495,
	"endColumn": 90,
	"modelVersionId": 59,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'deleteAlbumInput'.",
	"source": "ts",
	"startLineNumber": 500,
	"startColumn": 22,
	"endLineNumber": 500,
	"endColumn": 38,
	"modelVersionId": 59,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'setDeleteAlbumInput'.",
	"source": "ts",
	"startLineNumber": 501,
	"startColumn": 32,
	"endLineNumber": 501,
	"endColumn": 51,
	"modelVersionId": 59,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'album'.",
	"source": "ts",
	"startLineNumber": 502,
	"startColumn": 28,
	"endLineNumber": 502,
	"endColumn": 33,
	"modelVersionId": 59,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'setShowDeleteAlbum'.",
	"source": "ts",
	"startLineNumber": 507,
	"startColumn": 34,
	"endLineNumber": 507,
	"endColumn": 52,
	"modelVersionId": 59,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'setDeleteAlbumInput'.",
	"source": "ts",
	"startLineNumber": 507,
	"startColumn": 61,
	"endLineNumber": 507,
	"endColumn": 80,
	"modelVersionId": 59,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'handleDeleteAlbum'.",
	"source": "ts",
	"startLineNumber": 513,
	"startColumn": 26,
	"endLineNumber": 513,
	"endColumn": 43,
	"modelVersionId": 59,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'deleteAlbumInput'.",
	"source": "ts",
	"startLineNumber": 514,
	"startColumn": 27,
	"endLineNumber": 514,
	"endColumn": 43,
	"modelVersionId": 59,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'album'.",
	"source": "ts",
	"startLineNumber": 514,
	"startColumn": 48,
	"endLineNumber": 514,
	"endColumn": 53,
	"modelVersionId": 59,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'deletingAlbum'.",
	"source": "ts",
	"startLineNumber": 514,
	"startColumn": 63,
	"endLineNumber": 514,
	"endColumn": 76,
	"modelVersionId": 59,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'deletingAlbum'.",
	"source": "ts",
	"startLineNumber": 516,
	"startColumn": 18,
	"endLineNumber": 516,
	"endColumn": 31,
	"modelVersionId": 59,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "1128",
	"severity": 8,
	"message": "Declaration or statement expected.",
	"source": "ts",
	"startLineNumber": 523,
	"startColumn": 5,
	"endLineNumber": 523,
	"endColumn": 7,
	"modelVersionId": 59,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'main'.",
	"source": "ts",
	"startLineNumber": 523,
	"startColumn": 7,
	"endLineNumber": 523,
	"endColumn": 11,
	"modelVersionId": 59,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Expression expected.",
	"source": "ts",
	"startLineNumber": 524,
	"startColumn": 3,
	"endLineNumber": 524,
	"endColumn": 4,
	"modelVersionId": 59,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/brady/momento/src/app/space/[code]/album/[albumId]/page.tsx",
	"owner": "typescript",
	"code": "1128",
	"severity": 8,
	"message": "Declaration or statement expected.",
	"source": "ts",
	"startLineNumber": 525,
	"startColumn": 1,
	"endLineNumber": 525,
	"endColumn": 2,
	"modelVersionId": 59,
	"origin": "extHost1"
}]